site_name: LightGraphs.jl
site_author: Seth Bromberger
repo_url: https://github.com/JuliaGraphs/LightGraphs.jl/
theme: readthedocs
pages:
  - 'Getting Started': 'index.md'
  - 'Basic Functions': 'basicmeasures.md'
  - 'Operators': 'operators.md'
  - 'Path and Traversal': 'pathing.md'
  - 'Distance': 'distance.md'
  - 'Centrality Measures': 'centrality.md'
  - 'Linear Algebra': 'linalg.md'
  - 'Community Structures': 'community.md'
  - 'Flow and Cut': 'flowcut.md'
  - 'Graph Generators': 'generators.md'
  - 'Reading / Writing Graphs': 'persistence.md'
  - 'Integration with other packages': 'integration.md'
docs_dir: 'doc'
markdown_extensions:
  - extra
  - tables
  - fenced_code
extra_css:
  - LightGraphs.css
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
