site_name: LightGraphs.jl
site_author: Seth Bromberger
repo_url: https://github.com/JuliaGraphs/LightGraphs.jl/
docs_dir: 'build'

theme: material

extra:
  palette:
    primary: 'indigo'
    accent:  'blue'

pages:
  - 'Getting Started': 'index.md'
  - 'Basic Functions': 'basicmeasures.md'
  - 'Operators': 'operators.md'
  - 'Path and Traversal': 'pathing.md'
  - 'Distance': 'distance.md'
  - 'Centrality Measures': 'centrality.md'
  - 'Linear Algebra': 'linalg.md'
  - 'Matching': 'matching.md'
  - 'Community Structures': 'community.md'
  - 'Degeneracy': 'degeneracy.md'
  - 'Flow and Cut': 'flowcut.md'
  - 'Graph Generators': 'generators.md'
  - 'Reading / Writing Graphs': 'persistence.md'
  - 'Integration with other packages': 'integration.md'
  - 'Contributing': 'contributing.md'
  - 'License Information': 'license.md'

extra_css:
  - assets/Documenter.css

markdown_extensions:
  - extra
  - tables
  - fenced_code
  - mdx_math:
      enable_dollar_delimiter: True

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - assets/mathjaxhelper.js
